// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnivgomxndzkngvxatln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduaXZnb214bmR6a25ndnhhdGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzU4NzQsImV4cCI6MjA3MzExMTg3NH0.dV-BnjuMoqi_YZ8NXphlSBUShij0Jh8brHk1uvjTsAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});